/*
 * @file neural_wall_wetting.h
 * 
 * Neural Network Wall Wetting Controller with Delayed Reward Learning
 * 
 * This implementation uses a simple feedforward neural network (4->8->2) 
 * with delayed reward learning system that evaluates performance based on
 * actual lambda response after sufficient time for wall wetting effects.
 * 
 * @author Generated by RusEFI Neural System
 */

#pragma once

#include "neural_wall_wetting_state_generated.h"
#include "engine_module.h"
#include "rusefi_types.h"
#include "cyclic_buffer.h"
#include <rusefi/timer.h>

// Neural Network Architecture Constants
#define NEURAL_INPUT_SIZE 4      // MAP derivative, Lambda error, RPM, CLT
#define NEURAL_HIDDEN_SIZE 8     // Hidden layer neurons
#define NEURAL_OUTPUT_SIZE 2     // Beta correction, Tau correction

// Network size calculations
#define NEURAL_WEIGHTS_IH_SIZE (NEURAL_INPUT_SIZE * NEURAL_HIDDEN_SIZE)    // 4*8 = 32
#define NEURAL_WEIGHTS_HO_SIZE (NEURAL_HIDDEN_SIZE * NEURAL_OUTPUT_SIZE)   // 8*2 = 16
#define NEURAL_TOTAL_WEIGHTS (NEURAL_WEIGHTS_IH_SIZE + NEURAL_WEIGHTS_HO_SIZE) // 48
#define NEURAL_TOTAL_BIASES (NEURAL_HIDDEN_SIZE + NEURAL_OUTPUT_SIZE)      // 8+2 = 10

// Delayed Reward System Constants
#define TRANSIENT_BUFFER_SIZE 32      // Maximum pending transients
#define LAMBDA_SNAPSHOT_SIZE 6        // Lambda snapshots at different times
#define BETA_EVALUATION_TIME_MS 200   // Time to evaluate beta effects
#define TAU_EVALUATION_TIME_MS 2000   // Time to evaluate tau effects

// Learning and convergence constants
#define MIN_TRANSIENTS_FOR_LEARNING 5    // Minimum transients before learning
#define CONVERGENCE_WINDOW_SIZE 20       // Window for convergence tracking
#define MAX_LEARNING_RATE 0.1f           // Maximum learning rate
#define MIN_LEARNING_RATE 0.001f         // Minimum learning rate

/**
 * Transient record for delayed reward evaluation
 */
struct TransientRecord {
    uint32_t startTime;              // When transient was detected
    float neuralBetaCorr;            // Neural beta correction applied
    float neuralTauCorr;             // Neural tau correction applied
    float classicBetaCorr;           // Classic beta correction (for comparison)
    float classicTauCorr;            // Classic tau correction (for comparison)
    
    // Context at transient start
    float targetLambda;              // Target lambda at transient
    float contextRpm;                // RPM context
    float contextLoad;               // Load context
    float contextClt;                // Temperature context
    float transientMagnitude;        // Magnitude of the transient
    
    // Lambda snapshots for evaluation
    float lambdaSnapshots[LAMBDA_SNAPSHOT_SIZE];  // [50ms, 100ms, 200ms, 500ms, 1000ms, 2000ms]
    bool snapshotsCaptured[LAMBDA_SNAPSHOT_SIZE]; // Which snapshots are valid
    
    // Performance evaluation
    float neuralScore;               // Performance score of neural correction
    float classicScore;              // Performance score of classic correction
    bool completed;                  // Evaluation completed
    bool valid;                      // Record is valid
    
    TransientRecord() : startTime(0), neuralBetaCorr(1.0f), neuralTauCorr(1.0f), 
                       classicBetaCorr(1.0f), classicTauCorr(1.0f), targetLambda(1.0f),
                       contextRpm(0), contextLoad(0), contextClt(0), transientMagnitude(0),
                       neuralScore(0), classicScore(0), completed(false), valid(false) {
        for (int i = 0; i < LAMBDA_SNAPSHOT_SIZE; i++) {
            lambdaSnapshots[i] = 0.0f;
            snapshotsCaptured[i] = false;
        }
    }
};

/**
 * Simple feedforward neural network for wall wetting correction
 */
class SimpleNeuralNetwork {
private:
    // Network weights and biases (working copies in float precision)
    float weightsInputHidden[NEURAL_WEIGHTS_IH_SIZE];
    float weightsHiddenOutput[NEURAL_WEIGHTS_HO_SIZE];
    float biasesHidden[NEURAL_HIDDEN_SIZE];
    float biasesOutput[NEURAL_OUTPUT_SIZE];
    
    // Activation values for backpropagation
    float hiddenActivations[NEURAL_HIDDEN_SIZE];
    float outputActivations[NEURAL_OUTPUT_SIZE];
    float lastInputs[NEURAL_INPUT_SIZE];
    
    // Learning parameters
    float learningRate;
    bool initialized;
    
    // Activation functions
    float sigmoid(float x) const { return 1.0f / (1.0f + expf(-x)); }
    float sigmoidDerivative(float x) const { return x * (1.0f - x); }
    float relu(float x) const { return x > 0 ? x : 0; }
    float reluDerivative(float x) const { return x > 0 ? 1.0f : 0; }
    
public:
    SimpleNeuralNetwork();
    
    void initialize(float initialLearningRate = 0.01f);
    void forward(const float inputs[NEURAL_INPUT_SIZE], float outputs[NEURAL_OUTPUT_SIZE]);
    void backward(const float targets[NEURAL_OUTPUT_SIZE], float reward);
    void updateLearningRate(float newRate);
    
    // Weight management
    void getWeights(float* weights, float* biases) const;
    void setWeights(const float* weights, const float* biases);
    void randomizeWeights(float scale = 0.1f);
    
    bool isInitialized() const { return initialized; }
    float getLearningRate() const { return learningRate; }
};

/**
 * Delayed reward system for evaluating neural network performance
 */
class DelayedRewardSystem {
private:
    cyclic_buffer<TransientRecord, TRANSIENT_BUFFER_SIZE> pendingTransients;
    
    // Performance tracking
    float recentNeuralScores[CONVERGENCE_WINDOW_SIZE];
    float recentClassicScores[CONVERGENCE_WINDOW_SIZE];
    int scoreIndex;
    int scoreCount;
    
    // Snapshot timing (in milliseconds)
    static constexpr uint32_t snapshotTimes[LAMBDA_SNAPSHOT_SIZE] = {50, 100, 200, 500, 1000, 2000};
    
    float calculateTargetLambda() const;
    float estimateClassicPerformance(const TransientRecord& record) const;
    void calculatePerformanceScores(TransientRecord& record);
    
public:
    DelayedRewardSystem();
    
    void recordTransientStart(float neuralBeta, float neuralTau, 
                             float classicBeta, float classicTau,
                             float transientMagnitude);
    void updatePendingTransients(float currentLambda);
    bool hasCompletedTransients() const;
    TransientRecord getNextCompletedTransient();
    
    // Performance metrics
    float getAverageNeuralScore() const;
    float getAverageClassicScore() const;
    float getPerformanceRatio() const; // Neural/Classic performance ratio
    int getPendingCount() const { return pendingTransients.getCount(); }
    
    void reset();
};

/**
 * Main Neural Wall Wetting Controller
 */
class NeuralWallWettingController : public EngineModule, public neural_wall_wetting_state_s {
public:
    using interface_t = NeuralWallWettingController;
    
    NeuralWallWettingController();
    
    // EngineModule interface
    void onFastCallback() override;
    void onSlowCallback() override;
    void onIgnitionStateChanged(bool ignitionOn) override;
    
    // Main interface
    void getNeuralCorrections(float mapDerivative, float lambdaError, 
                             float rpm, float clt,
                             float& betaCorrection, float& tauCorrection);
    
    bool isEnabled() const;
    bool isLearning() const;
    bool hasConverged() const;
    
    // Configuration and persistence
    void saveWeightsToConfig();
    void loadWeightsFromConfig();
    
    // IWallFuelController interface requirement
    void onActualFuelInjection(float injectedMass, int cylinderIndex = 0);
    
private:
    // Core components
    SimpleNeuralNetwork neuralNetwork;
    DelayedRewardSystem rewardSystem;
    
    // State management
    bool enabled;
    bool learning;
    bool ignitionState;
    Timer ignitionOffTimer;
    bool pendingSave;
    
    // Transient detection
    float lastMapValue;
    Timer transientDetectionTimer;
    bool transientActive;
    float currentTransientMagnitude;
    
    // Learning control
    float adaptiveLearningRate;
    uint32_t totalTrainingSteps;
    uint32_t convergenceCounter;
    
    // Performance tracking
    float performanceHistory[CONVERGENCE_WINDOW_SIZE];
    int performanceIndex;
    int performanceCount;
    
    // Debug tracking for injection correlation
    float debugLastInjectedMass;
    int debugLastCylinderIndex;
    
    // Configuration access helpers
    bool getConfigEnabled() const;
    float getConfigLearningRate() const;
    float getConfigMinConfidence() const;
    float getConfigTransientThreshold() const;
    
    // Core logic
    void detectTransients();
    void processLearning();
    void updatePerformanceMetrics();
    void adaptLearningRate();
    
    // Classic system interface
    void getClassicCorrections(float rpm, float load, float& betaCorr, float& tauCorr) const;
    
    // Note: quantizeWeights/dequantizeWeights not needed with autoscale
    // RusEFI autoscale fields provide automatic conversion via scaled_channel
    
    // Validation and limits
    bool validateInputs(float mapDerivative, float lambdaError, float rpm, float clt) const;
    void clampOutputs(float& betaCorrection, float& tauCorrection) const;
    
    // Debug and diagnostics
    void updateDebugInfo();
    void logPerformanceMetrics() const;
};

// Global instance access function
NeuralWallWettingController& getNeuralWallWettingController(); 